export const GOT_ERROR = "GOT_ERROR";
export const CONSUMED_ERROR = "CONSUMED_ERROR";

// user auth
export const FETCH_USER = "FETCH_USER";
export const LOGOUT_USER = "LOGOUT_USER";

export const CREATE_METAMODULE = "CREATE_METAMODULE";

export const CREATE_MODULE_INSTANCE = "CREATE_MODULE_INSTANCE";

// Document module stuff
export const ADD_DOCUMENT_MODULE = "ADD_DOCUMENT_MODULE";
export const REMOVE_DOCUMENT_MODULE = "REMOVE_DOCUMENT_MODULE";
export const ADD_QUESTION_TO_DOCUMENT_MODULE =
  "ADD_QUESTION_TO_DOCUMENT_MODULE";
export const ADD_EXAMPLE_TO_DOCUMENT_MODULE = "ADD_EXAMPLE_TO_DOCUMENT_MODULE";

export const DOCUMENT_MODULE_LOADING = "DOCUMENT_MODULE_LOADING";

// For LearningAids
export const CREATE_QUESTION = "CREATE_QUESTION";
export const CREATE_RESPONSE = "CREATE_RESPONSE";
export const CREATE_SOLUTION = "CREATE_SOLUTION";
export const CREATE_EXAMPLE = "CREATE_EXAMPLE";

export const CREATE_EXAMPLE_PROBLEM = "CREATE_EXAMPLE_PROBLEM";
export const CREATE_EXAMPLE_SOLUTION = "CREATE_EXAMPLE_SOLUTION";

export const GET_QUESTIONS = "GET_QUESTIONS";
export const QUESTIONS_LOADING = "QUESTIONS_LOADING";

export const GET_EXAMPLES = "GET_EXAMPLES";
export const EXAMPLES_LOADING = "EXAMPLES_LOADING";

export const CREATE_METAMODULE_THOUGHT = "CREATE_METAMODULE_THOUGHT";
export const GET_METAMODULE_THOUGHTS = "GET_METAMODULE_THOUGHTS";
export const METAMODULE_THOUGHTS_LOADING = "METAMODULE_THOUGHTS_LOADING";

// VOTES
export const GET_USER_VOTES = "GET_USER_VOTES";
export const USER_VOTES_LOADING = "USER_VOTES_LOADING";
export const CREATE_UP_DOWN_VOTE = "CREATE_UP_DOWN_VOTE";
export const DELETE_UP_DOWN_VOTE = "DELETE_UP_DOWN_VOTE";

export const OPEN_SIDE_NAV_RIGHT = "OPEN_SIDE_NAV_RIGHT";
export const CLOSE_SIDE_NAV_RIGHT = "CLOSE_SIDE_NAV_RIGHT";

// TREE
export const OPEN_SORTABLE_TREE = "OPEN_SORTABLE_TREE";
export const CLOSE_SORTABLE_TREE = "CLOSE_SORTABLE_TREE";
export const CHANGE_FLATTENED_TREE = "CHANGE_FLATTENED_TREE";

// TABS
export const ADD_TAB_TO_DOCUMENT_MODULE = "ADD_TAB_TO_DOCUMENT_MODULE";
export const REMOVE_TAB_FROM_DOCUMENT_MODULE =
  "REMOVE_TAB_FROM_DOCUMENT_MODULE";

// TEXTBOOKS
export const CREATE_TEXTBOOK = "CREATE_TEXTBOOK";
export const CREATE_TEXTBOOK_LOADING = "CREATE_TEXTBOOK_LOADING";
export const UPDATE_TEXTBOOK = "UPDATE_TEXTBOOK";
export const DELETE_TEXTBOOK = "DELETE_TEXTBOOK";
export const GET_MY_TEXTBOOKS = "GET_MY_TEXTBOOKS";
export const GET_PUBLIC_TEXTBOOKS = "GET_PUBLIC_TEXTBOOKS";
export const PUBLIC_TEXTBOOKS_LOADING = "PUBLIC_TEXTBOOKS_LOADING";
export const MY_TEXTBOOKS_LOADING = "MY_TEXTBOOKS_LOADING";
export const UPDATE_TEXTBOOK_LOADING = "UPDATE_TEXTBOOK_LOADING";
export const DELETE_TEXTBOOK_LOADING = "DELETE_TEXTBOOK_LOADING";

export const DOWNLOAD_TEXTBOOK_LOADING = "DOWNLOAD_TEXTBOOK_LOADING";
export const DOWNLOAD_TEXTBOOK_DONE = "DOWNLOAD_TEXTBOOK_DONE";

// this is for adding document module when downloading textbook
export const DOWNLOADING_ADD_DOCUMENT_MODULE =
  "DOWNLOADING_ADD_DOCUMENT_MODULE";

export const COPY_TEXTBOOK_FROM_PUBLIC = "COPY_TEXTBOOK_FROM_PUBLIC";
export const COPY_TEXTBOOK_FROM_PUBLIC_LOADING =
  "COPY_TEXTBOOK_FROM_PUBLIC_LOADING";

export const CHANGE_SECTION_TITLE = "CHANGE_SECTION_TITLE";

// Types for handling inutitive functionality with creation events
export const CREATE_QUESTION_LOADING = "CREATE_QUESTION_LOADING";
export const CREATE_EXAMPLE_LOADING = "CREATE_EXAMPLE_LOADING";
export const CREATE_RESPONSE_LOADING = "CREATE_RESPONSE_LOADING";
export const CREATE_SOLUTION_LOADING = "CREATE_SOLUTION_LOADING";
export const CREATE_METAMODULE_THOUGHT_LOADING =
  "CREATE_METAMODULE_THOUGHT_LOADING";

export const REMOVE_LEARNING_AIDS_CREATE_EVENT =
  "REMOVE_LEARNING_AIDS_CREATE_EVENT";
export const CREATE_METAMODULE_LOADING = "CREATE_METAMODULE_LOADING";
export const CREATE_MODULE_INSTANCE_LOADING = "CREATE_MODULE_INSTANCE_LOADING";
export const REMOVE_DOCUMENT_CREATE_EVENT = "REMOVE_DOCUMENT_CREATE_EVENT";

// DELETING AND EDITING
export const DELETE_RESPONSE = "DELETE_RESPONSE";
export const DELETE_RESPONSE_LOADING = "DELETE_RESPONSE_LOADING";
export const DELETE_SOLUTION = "DELETE_SOLUTION";
export const DELETE_SOLUTION_LOADING = "DELETE_SOLUTION_LOADING";
export const DELETE_QUESTION = "DELETE_QUESTION";
export const DELETE_QUESTION_LOADING = "DELETE_QUESTION_LOADING";
export const DELETE_EXAMPLE = "DELETE_EXAMPLE";
export const DELETE_EXAMPLE_LOADING = "DELETE_EXAMPLE_LOADING";
export const DELETE_METAMODULE_THOUGHT = "DELETE_METAMODULE_THOUGHT";
export const DELETE_METAMODULE_THOUGHT_LOADING =
  "DELETE_METAMODULE_THOUGHT_LOADING";
export const DELETE_MODULE_INSTANCE_LOADING = "DELETE_MODULE_INSTANCE_LOADING";
export const DELETE_MODULE_INSTANCE = "DELETE_MODULE_INSTANCE";
export const REMOVE_DOCUMENT_DELETE_EVENT = "REMOVE_DOCUMENT_DELETE_EVENT";

export const DELETE_METAMODULE = "DELETE_METAMODULE";

export const EDIT_QUESTION = "EDIT_QUESTION";
export const EDIT_QUESTION_LOADING = "EDIT_QUESTION_LOADING";
export const EDIT_EXAMPLE = "EDIT_EXAMPLE";
export const EDIT_EXAMPLE_LOADING = "EDIT_EXAMPLE_LOADING";
export const EDIT_RESPONSE = "EDIT_RESPONSE";
export const EDIT_RESPONSE_LOADING = "EDIT_RESPONSE_LOADING";
export const EDIT_SOLUTION = "EDIT_SOLUTION";
export const EDIT_SOLUTION_LOADING = "EDIT_SOLUTION_LOADING";
// export const EDIT_METAMODULE_THOUGHT = "EDIT_METAMODULE_THOUGHT";
// export const EDIT_METAMODULE_THOUGHT_LOADING =
//   "EDIT_METAMODULE_THOUGHT_LOADING";
export const REMOVE_LEARNING_AIDS_EDIT_EVENT =
  "REMOVE_LEARNING_AIDS_EDIT_EVENT";

export const EDIT_MODULE_INSTANCE = "EDIT_MODULE_INSTANCE";
export const EDIT_MODULE_INSTANCE_LOADING = "EDIT_MODULE_INSTANCE_LOADING";

export const REMOVE_DOCUMENT_EDIT_EVENT = "REMOVE_DOCUMENT_EDIT_EVENT";

// For notifying of events (that dont need specific actions to be taken
// when consumed -- they just need to be consumed, like deleting responses)
export const CONSUMED_EVENT = "CONSUMED_EVENT";

export const REFRESH_METAMODULE = "REFRESH_METAMODULE";
export const REFRESH_METAMODULE_LOADING = "REFRESH_METAMODULE_LOADING";

export const CLEAR_QUESTION_EVENTS = "CLEAR_QUESTION_EVENTS";
export const CLEAR_EXAMPLE_EVENTS = "CLEAR_EXAMPLE_EVENTS";
